In [1]:
# Dependencies
import numpy as np
import pandas as pd

## Data Pre-Processing

In [2]:
crime = pd.read_csv('la_crime_incl_fbi_violent.csv')
crime = crime.drop([0])
#crime = crime.set_index('dr_no')
crime['date_occ'] = crime['date_occ'].apply(pd.to_numeric)
crime['status'] = crime['status'].fillna('-')
crime['vict_sex'] = crime['vict_sex'].fillna('-')
crime['vict_descent'] = crime['vict_descent'].fillna('-')
crime

,dr_no,area_id,date_occ,date_rptd,longitude,latitude,mocodes,premis_cd,rpt_dist_no,status,hour_occ,minute_occ,vict_age,vict_descent,vict_sex,fbi_part_1
1,214,14,20170801,20170801,-118.4262,34.0106,NaN,104.0,1435,IC,2,0,16.0,-,-,Property
2,405,5,20181031,20181102,-118.2468,33.7926,NaN,101.0,519,IC,21,0,17.0,-,-,Property
3,415,15,20170822,20170822,-118.4137,34.1867,NaN,108.0,1523,IC,13,45,16.0,-,-,Property
4,418,18,20130318,20130319,-118.2717,33.9420,NaN,101.0,1823,IC,20,30,12.0,-,-,Property
5,605,5,20120606,20120607,-118.2640,33.8028,NaN,101.0,518,IC,23,0,11.0,-,-,Property
6,809,9,20150116,20150117,-118.4263,34.1814,NaN,108.0,938,IC,21,30,14.0,-,-,Property
7,1009,3,20100320,20100321,-118.3156,34.0246,NaN,101.0,355,IC,23,0,NaN,-,-,Property
8,1105,5,20101118,20110224,-118.2846,33.7289,NaN,121.0,567,IC,20,0,NaN,-,-,Property
9,1505,5,20151030,20151130,-118.2842,33.7167,NaN,710.0,589,IC,12,0,14.0,-,-,Property
10,1512,12,20150713,20150713,-118.2893,33.9995,NaN,124.0,1207,IC,9,45,14.0,-,M,Property
11,1712,12,20170902,20170907,-118.2918,33.9665,NaN,101.0,1265,IC,13,0,16.0,-,-,Property
12,80611351,6,20110612,20110613,-118.3348,34.1032,"[""0344"", ""1607""]",502.0,636,IC,21,30,22.0,H,M,Property
13,91231932,3,20110514,20110514,-118.3290,34.0060,"[""0430"", ""1100"", ""1414"", ""0906""]",735.0,393,IC,3,30,52.0,B,M,Violent
14,100100506,1,20100104,20100105,-118.2577,34.0480,"[""0344"", ""1402""]",404.0,162,AA,16,50,23.0,B,M,Property
15,100100508,1,20100107,20100108,-118.2643,34.0389,"[""0344""]",101.0,182,IC,20,5,47.0,H,M,Property
16,100100509,1,20100108,20100109,-118.2427,34.0435,"[""0416""]",710.0,157,AA,21,0,51.0,B,M,Violent
17,100100510,1,20100109,20100109,-118.2640,34.0450,"[""0400"", ""0416""]",108.0,171,IC,2,30,30.0,H,M,Violent
18,100100522,1,20100114,20100115,-118.2386,34.0350,"[""0344""]",101.0,158,AO,20,0,40.0,H,M,Violent
19,100100531,1,20100115,20100116,-118.2424,34.0515,"[""0344"", ""0416"", ""1218""]",102.0,127,IC,20,30,47.0,A,M,Violent
20,100100553,1,20100123,20100123,-118.2461,34.0428,"[""0344"", ""0416""]",101.0,166,IC,11,0,50.0,W,M,Violent
21,100100555,1,20100123,20100123,-118.2499,34.0545,"[""2000""]",502.0,132,IC,20,0,18.0,W,F,Violent
22,100100561,1,20100126,20100126,-118.2374,34.0563,"[""0346"", ""0400""]",102.0,119,AA,18,20,37.0,H,M,Violent
23,100100564,1,20100129,20100130,-118.2360,34.0454,"[""0344"", ""1609""]",101.0,139,IC,16,30,25.0,W,F,Property
24,100100570,1,20100131,20100131,-118.2371,34.0472,"[""0344""]",210.0,139,IC,1,30,31.0,H,M,Property
25,100100572,1,20100131,20100201,-118.2452,34.0423,"[""0416""]",102.0,166,AO,17,0,61.0,B,F,Violent
26,100100591,1,20100208,20100210,-118.2654,34.0415,"[""0344"", ""1609""]",108.0,182,IC,16,25,22.0,W,F,Property
27,100100592,1,20100208,20100208,-118.2577,34.0480,"[""0344""]",203.0,162,AA,18,0,23.0,H,M,Property
28,100100608,1,20100210,20100211,-118.2574,34.0502,"[""0416""]",210.0,152,AA,19,0,27.0,H,M,Violent
29,100100610,1,20100210,20100211,-118.2577,34.0480,"[""0325"", ""1402""]",404.0,162,AA,18,0,24.0,B,M,Property
30,100100628,1,20100214,20100215,-118.2412,34.0426,"[""0408""]",502.0,158,AA,15,0,40.0,H,M,Violent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946949,182119246,21,20181030,20181113,-118.6010,34.2247,"[""0344"", ""0394""]",119.0,2105,IC,18,25,36.0,W,M,Property
946950,182119247,21,20181030,20181114,-118.6168,34.1701,"[""0344"", ""0377""]",101.0,2175,IC,19,30,49.0,H,M,Property
946951,182119251,21,20181113,20181114,-118.5787,34.1683,"[""0344"", ""1307""]",707.0,2189,IC,23,0,34.0,W,M,Property
946952,182119252,21,20181113,20181114,-118.5787,34.1683,"[""0344"", ""0352"", ""1307""]",108.0,2189,IC,21,0,25.0,B,F,Property
946953,182119253,21,20181114,20181114,-118.5799,34.2162,"[""0344""]",301.0,2118,IC,12,40,53.0,W,M,Property
946954,182119254,21,20181114,20181114,-118.5943,34.1974,"[""0416"", ""0314"", ""1259""]",501.0,2146,IC,10,20,17.0,H,M,Property
946955,182119255,21,20181113,20181114,-118.6308,34.2024,"[""0344""]",203.0,2133,IC,19,0,62.0,X,M,Property
946956,182119260,21,20181031,20181114,-118.5754,34.2120,"[""1501""]",202.0,2128,IC,12,0,41.0,X,M,Property
946957,182119261,21,20180810,20181114,-118.5656,34.2116,"[""0377""]",501.0,2129,IC,12,0,58.0,O,F,Property
946958,182119262,21,20181114,20181114,-118.5669,34.1637,"[""0344"", ""0352"", ""0321"", ""1609""]",501.0,2189,IC,22,10,58.0,W,F,Property
946959,182119268,21,20181114,20181115,-118.5994,34.1974,NaN,101.0,2146,IC,17,30,17.0,-,-,Property
946960,182119270,21,20181113,20181115,-118.5792,34.2047,NaN,108.0,2138,IC,1,30,17.0,-,-,Property
946961,182119271,21,20181111,20181114,-118.5884,34.1938,"[""0344""]",301.0,2157,IC,12,0,27.0,O,M,Property
946962,182119272,21,20181115,20181115,-118.6277,34.1828,NaN,101.0,2143,IC,1,0,17.0,-,-,Property
946963,182119274,21,20181114,20181114,-118.5627,34.2108,"[""0344""]",104.0,2129,IC,1,55,38.0,W,M,Property
946964,182119275,21,20181111,20181112,-118.6081,34.2024,"[""0344"", ""1606"", ""0386""]",707.0,2134,IC,13,0,31.0,H,M,Property
946965,182119277,21,20181110,20181112,-118.5884,34.1884,"[""0344"", ""0321""]",123.0,2158,IC,22,0,38.0,W,F,Property
946966,182119283,21,20181114,20181115,-118.6157,34.1905,"[""1307"", ""0344""]",101.0,2144,IC,22,15,58.0,H,M,Property
946967,182119284,21,20181113,20181115,-118.6274,34.1883,"[""0344""]",108.0,2143,IC,13,15,25.0,W,F,Property
946968,182119285,21,20181115,20181115,-118.5941,34.1912,NaN,108.0,2157,IC,17,30,17.0,-,-,Property
946969,182119286,21,20181115,20181115,-118.6196,34.2137,"[""0344"", ""1912""]",502.0,2113,IC,11,0,44.0,O,M,Property
946970,182119287,21,20181114,20181115,-118.5928,34.1847,"[""1202"", ""2032"", ""0344"", ""0377""]",243.0,2158,IC,14,0,81.0,W,M,Property
946971,182119288,21,20181031,20181115,-118.6274,34.1883,"[""1202"", ""0344"", ""0377""]",402.0,2143,IC,12,0,81.0,W,F,Property
946972,182119290,21,20181108,20181108,-118.5645,34.2012,"[""0329"", ""1271"", ""0344""]",501.0,2139,IC,11,50,29.0,W,M,Property
946973,182119295,21,20181115,20181115,-118.5823,34.1938,"[""1606"", ""0344"", ""2004""]",108.0,2157,AA,8,0,30.0,H,F,Property
946974,182119306,21,20181109,20181115,-118.6168,34.1535,"[""0349""]",501.0,2183,IC,15,25,73.0,W,M,Property
946975,182119307,21,20181114,20181115,-118.6135,34.2034,"[""1609"", ""0344"", ""0321""]",203.0,2134,IC,19,30,35.0,X,M,Property
946976,182119365,21,20181110,20181117,-118.6325,34.1601,NaN,101.0,2183,IC,13,0,17.0,-,-,Property
946977,189917035,4,20180428,20180502,-118.2204,34.0819,NaN,101.0,412,AA,9,0,19.0,-,M,Property
946978,910220366,4,20110809,20110809,-118.2144,34.0606,"[""1402""]",725.0,443,IC,8,0,NaN,X,X,Violent

In [3]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
crime = crime.join(pd.DataFrame(mlb.fit_transform(crime.pop('vict_descent')),
                               columns=mlb.classes_ + "(vict_descent)",
                               index=crime.index))

crime = crime.join(pd.DataFrame(mlb.fit_transform(crime.pop('vict_sex')),
                               columns=mlb.classes_ + "(vict_sex)",
                               index=crime.index))

crime = crime.join(pd.DataFrame(mlb.fit_transform(crime.pop('status')),
                               columns=mlb.classes_ + "(status)",
                               index=crime.index))

crime.head()

,dr_no,area_id,date_occ,date_rptd,longitude,latitude,mocodes,premis_cd,rpt_dist_no,hour_occ,...,X(vict_sex),-(status),1(status),3(status),9(status),A(status),C(status),I(status),J(status),O(status)
1,214,14,20170801,20170801,-118.4262,34.0106,NaN,104.0,1435,2,...,0,0,0,0,0,0,1,1,0,0
2,405,5,20181031,20181102,-118.2468,33.7926,NaN,101.0,519,21,...,0,0,0,0,0,0,1,1,0,0
3,415,15,20170822,20170822,-118.4137,34.1867,NaN,108.0,1523,13,...,0,0,0,0,0,0,1,1,0,0
4,418,18,20130318,20130319,-118.2717,33.9420,NaN,101.0,1823,20,...,0,0,0,0,0,0,1,1,0,0
5,605,5,20120606,20120607,-118.2640,33.8028,NaN,101.0,518,23,...,0,0,0,0,0,0,1,1,0,0

In [4]:
crime['mocodes'].isna().sum()

175950

In [5]:
#crime['mocodes'] = crime['mocodes'].fillna('["-"]')
crime['mocodes'].isna().sum()
crime = crime.dropna()
crime.count()

dr_no              714750
area_id            714750
date_occ           714750
date_rptd          714750
longitude          714750
latitude           714750
mocodes            714750
premis_cd          714750
rpt_dist_no        714750
hour_occ           714750
minute_occ         714750
vict_age           714750
fbi_part_1         714750
-(vict_descent)    714750
A(vict_descent)    714750
B(vict_descent)    714750
C(vict_descent)    714750
D(vict_descent)    714750
F(vict_descent)    714750
G(vict_descent)    714750
H(vict_descent)    714750
I(vict_descent)    714750
J(vict_descent)    714750
K(vict_descent)    714750
L(vict_descent)    714750
O(vict_descent)    714750
P(vict_descent)    714750
S(vict_descent)    714750
U(vict_descent)    714750
V(vict_descent)    714750
W(vict_descent)    714750
X(vict_descent)    714750
Z(vict_descent)    714750
-(vict_sex)        714750
F(vict_sex)        714750
H(vict_sex)        714750
M(vict_sex)        714750
N(vict_sex)        714750
X(vict_sex)        714750
-(status)          714750
1(status)          714750
3(status)          714750
9(status)          714750
A(status)          714750
C(status)          714750
I(status)          714750
J(status)          714750
O(status)          714750
dtype: int64

## One-hot Encode mocodes

In [6]:
from sklearn.preprocessing import LabelEncoder

mocodes = crime.values[:, 7]

label_encoder = LabelEncoder()
label_encoder.fit(mocodes)
mocodes2 = label_encoder.transform(mocodes)
mocodes2

array([136, 196, 120, ...,   7, 135,  59], dtype=int64)

In [7]:
from keras.utils import to_categorical

mocodes3 = to_categorical(mocodes2)
mocodes3

Using TensorFlow backend.

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
for label, original_class in zip(mocodes3, mocodes):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [8]:
new_mocodes = pd.DataFrame(mocodes3)
new_mocodes.head()

,0,1,2,3,4,5,6,7,8,9,...,296,297,298,299,300,301,302,303,304,305
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
crime = pd.merge(crime, new_mocodes, left_index=True, right_index=True)

crime

,dr_no,area_id,date_occ,date_rptd,longitude,latitude,mocodes,premis_cd,rpt_dist_no,hour_occ,...,296,297,298,299,300,301,302,303,304,305
12,80611351,6,20110612,20110613,-118.3348,34.1032,"[""0344"", ""1607""]",502.0,636,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,91231932,3,20110514,20110514,-118.3290,34.0060,"[""0430"", ""1100"", ""1414"", ""0906""]",735.0,393,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,100100506,1,20100104,20100105,-118.2577,34.0480,"[""0344"", ""1402""]",404.0,162,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,100100508,1,20100107,20100108,-118.2643,34.0389,"[""0344""]",101.0,182,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,100100509,1,20100108,20100109,-118.2427,34.0435,"[""0416""]",710.0,157,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,100100510,1,20100109,20100109,-118.2640,34.0450,"[""0400"", ""0416""]",108.0,171,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,100100522,1,20100114,20100115,-118.2386,34.0350,"[""0344""]",101.0,158,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,100100531,1,20100115,20100116,-118.2424,34.0515,"[""0344"", ""0416"", ""1218""]",102.0,127,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,100100553,1,20100123,20100123,-118.2461,34.0428,"[""0344"", ""0416""]",101.0,166,11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,100100555,1,20100123,20100123,-118.2499,34.0545,"[""2000""]",502.0,132,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,100100561,1,20100126,20100126,-118.2374,34.0563,"[""0346"", ""0400""]",102.0,119,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,100100564,1,20100129,20100130,-118.2360,34.0454,"[""0344"", ""1609""]",101.0,139,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,100100570,1,20100131,20100131,-118.2371,34.0472,"[""0344""]",210.0,139,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,100100572,1,20100131,20100201,-118.2452,34.0423,"[""0416""]",102.0,166,17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,100100591,1,20100208,20100210,-118.2654,34.0415,"[""0344"", ""1609""]",108.0,182,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100100592,1,20100208,20100208,-118.2577,34.0480,"[""0344""]",203.0,162,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,100100608,1,20100210,20100211,-118.2574,34.0502,"[""0416""]",210.0,152,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,100100610,1,20100210,20100211,-118.2577,34.0480,"[""0325"", ""1402""]",404.0,162,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,100100628,1,20100214,20100215,-118.2412,34.0426,"[""0408""]",502.0,158,15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,100100630,1,20100215,20100215,-118.2466,34.0544,"[""0400""]",101.0,123,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,100100650,1,20100225,20100225,-118.2469,34.0617,"[""0344"", ""1251""]",502.0,111,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,100100651,1,20100225,20100226,-118.2496,34.0394,"[""0416"", ""0429""]",108.0,176,23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,100100672,1,20100306,20100306,-118.2560,34.0535,"[""0413"", ""0500"", ""0536"", ""0526""]",503.0,142,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,100100694,1,20100312,20100312,-118.2471,34.0435,"[""0416"", ""0411"", ""0417"", ""1402""]",101.0,166,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,100100708,1,20100314,20100314,-118.2468,34.0407,"[""0337"", ""0400"", ""0411"", ""0432"", ""0906""]",102.0,166,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,100100724,1,20100318,20100318,-118.2472,34.0482,"[""0400""]",210.0,145,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,100100725,1,20100318,20100318,-118.2472,34.0482,"[""0400""]",210.0,145,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,100100728,1,20100319,20100319,-118.2450,34.0446,"[""0305"", ""0344"", ""0416""]",504.0,147,11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,100100731,1,20100321,20100321,-118.2458,34.0635,"[""0344"", ""0906"", ""1402"", ""1609""]",101.0,111,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,100100740,1,20100322,20100325,-118.2526,34.0516,"[""0416""]",101.0,142,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714705,162111296,21,20160606,20160607,-118.6059,34.1850,"[""0444"", ""0325"", ""0945""]",406.0,2156,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714706,162111309,21,20160607,20160607,-118.6059,34.1905,"[""1822"", ""0930""]",406.0,2156,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714707,162111311,21,20160606,20160607,-118.5941,34.1912,"[""0344"", ""1602""]",101.0,2157,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714708,162111312,21,20160607,20160607,-118.6084,34.1720,"[""1607"", ""0344""]",501.0,2175,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714709,162111314,21,20160606,20160607,-118.6234,34.1864,"[""0344"", ""0377"", ""1202""]",243.0,2143,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714710,162111323,21,20160606,20160607,-118.6274,34.1883,"[""0344""]",108.0,2143,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714711,162111337,21,20160607,20160607,-118.6251,34.1616,"[""0344"", ""1609""]",501.0,2183,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714714,162111418,21,20160608,20160608,-118.5908,34.1667,"[""0344""]",402.0,2187,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714715,162111419,21,20160526,20160608,-118.5859,34.1665,"[""0325""]",404.0,2189,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714716,162111427,21,20160605,20160607,-118.5732,34.2035,"[""0344""]",108.0,2139,23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714717,162111431,21,20160522,20160608,-118.5950,34.1496,"[""0344"", ""1607""]",501.0,2196,14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714718,162111432,21,20160608,20160608,-118.5710,34.1938,"[""0352"", ""0344"", ""1607""]",501.0,2149,14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714719,162111439,21,20160608,20160608,-118.6274,34.1883,"[""1402"", ""0325""]",101.0,2143,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714720,162111443,21,20160601,20160608,-118.5928,34.2011,"[""0344""]",101.0,2136,14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714721,162111444,21,20160608,20160608,-118.5699,34.1957,"[""0344""]",501.0,2149,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714722,162111445,21,20160608,20160608,-118.5738,34.2044,"[""0344"", ""0321""]",501.0,2139,15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714727,162111478,21,20160516,20160609,-118.5787,34.1683,"[""0344"", ""0394""]",502.0,2189,12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714729,162111487,21,20160609,20160609,-118.5847,34.1968,"[""1609"", ""0321"", ""0344""]",501.0,2147,12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714730,162111488,21,20160608,20160609,-118.5943,34.2010,"[""0344""]",108.0,2146,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714731,162111489,21,20160528,20160609,-118.6408,34.1701,"[""1202"", ""1609""]",501.0,2172,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714733,162111504,21,20160608,20160609,-118.6077,34.1848,"[""0344"", ""0394""]",502.0,2155,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714734,162111505,21,20160609,20160609,-118.5688,34.2047,"[""0344""]",708.0,2139,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714735,162111507,21,20160609,20160609,-118.6044,34.1938,"[""0325""]",404.0,2156,17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714736,162111516,21,20160609,20160609,-118.6103,34.2139,"[""0344"", ""1402""]",402.0,2114,23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714738,162111526,21,20160609,20160609,-118.5863,34.2083,"[""1606"", ""1607"", ""0344"", ""0321""]",501.0,2137,11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714739,162111528,21,20160609,20160610,-118.5640,34.1737,"[""0913"", ""0411"", ""1810"", ""0337""]",501.0,2169,23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714740,162111529,21,20160610,20160610,-118.6227,34.2200,"[""0344"", ""1202""]",501.0,2103,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714744,162111537,21,20160602,20160610,-118.5806,34.1565,"[""0923"", ""1822"", ""1202""]",501.0,2196,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714748,162111559,21,20160610,20160610,-118.6017,34.2119,"[""0344"", ""1609"", ""1307""]",123.0,2125,17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714749,162111560,21,20160609,20160610,-118.5710,34.2035,"[""0344"", ""1607""]",108.0,2139,23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
crime = crime.drop("mocodes", axis=1)

In [11]:
crime['vict_age'].isna().sum()

0

In [12]:
crime_cln = crime.dropna()

In [13]:
X = crime_cln.drop("fbi_part_1", axis=1)
y = crime_cln["fbi_part_1"]
print(X.shape, y.shape)

(539619, 352) (539619,)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

# Create a Deep Learning Model

In [15]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=352))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [16]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 17s - loss: 0.4167 - acc: 0.8145
Epoch 2/100
 - 16s - loss: 0.3956 - acc: 0.8245
Epoch 3/100
 - 16s - loss: 0.3870 - acc: 0.8299
Epoch 4/100
 - 16s - loss: 0.3823 - acc: 0.8328
Epoch 5/100
 - 16s - loss: 0.3795 - acc: 0.8341
Epoch 6/100
 - 16s - loss: 0.3774 - acc: 0.8349
Epoch 7/100
 - 16s - loss: 0.3756 - acc: 0.8362
Epoch 8/100
 - 16s - loss: 0.3741 - acc: 0.8371
Epoch 9/100
 - 16s - loss: 0.3728 - acc: 0.8376
Epoch 10/100
 - 17s - loss: 0.3718 - acc: 0.8382
Epoch 11/100
 - 17s - loss: 0.3703 - acc: 0.8388
Epoch 12/100
 - 17s - loss: 0.3693 - acc: 0.8393
Epoch 13/100
 - 17s - loss: 0.3683 - acc: 0.8400
Epoch 14/100
 - 17s - loss: 0.3676 - acc: 0.8405
Epoch 15/100
 - 18s - loss: 0.3665 - acc: 0.8411
Epoch 16/100
 - 18s - loss: 0.3664 - acc: 0.8410
Epoch 17/100
 - 18s - loss: 0.3658 - acc: 0.8412
Epoch 18/100
 - 18s - loss: 0.3650 - acc: 0.8418
Epoch 19/100
 - 18s - loss: 0.3643 - acc: 0.8421
Epoch 20/100
 - 18s - loss: 0.3637 - acc: 0.8424
Epoch 21/100
 - 18s - loss: 0.3634 - acc: 0.8426
Epoch 22/100
 - 19s - loss: 0.3628 - acc: 0.8430
Epoch 23/100
 - 19s - loss: 0.3629 - acc: 0.8428
Epoch 24/100
 - 19s - loss: 0.3622 - acc: 0.8431
Epoch 25/100
 - 18s - loss: 0.3628 - acc: 0.8435
Epoch 26/100
 - 18s - loss: 0.3613 - acc: 0.8436
Epoch 27/100
 - 18s - loss: 0.3611 - acc: 0.8440
Epoch 28/100
 - 18s - loss: 0.3605 - acc: 0.8441
Epoch 29/100
 - 18s - loss: 0.3600 - acc: 0.8441
Epoch 30/100
 - 18s - loss: 0.3600 - acc: 0.8440
Epoch 31/100
 - 18s - loss: 0.3601 - acc: 0.8441
Epoch 32/100
 - 18s - loss: 0.3592 - acc: 0.8446
Epoch 33/100
 - 20s - loss: 0.3592 - acc: 0.8447
Epoch 34/100
 - 20s - loss: 0.3585 - acc: 0.8446
Epoch 35/100
 - 19s - loss: 0.3582 - acc: 0.8448
Epoch 36/100
 - 19s - loss: 0.3587 - acc: 0.8453
Epoch 37/100
 - 19s - loss: 0.3578 - acc: 0.8457
Epoch 38/100
 - 19s - loss: 0.3573 - acc: 0.8454
Epoch 39/100
 - 19s - loss: 0.3574 - acc: 0.8455
Epoch 40/100
 - 19s - loss: 0.3574 - acc: 0.8463
Epoch 41/100
 - 19s - loss: 0.3567 - acc: 0.8460
Epoch 42/100
 - 19s - loss: 0.3565 - acc: 0.8458
Epoch 43/100
 - 19s - loss: 0.3567 - acc: 0.8458
Epoch 44/100
 - 20s - loss: 0.3561 - acc: 0.8461
Epoch 45/100
 - 19s - loss: 0.3564 - acc: 0.8464
Epoch 46/100
 - 19s - loss: 0.3559 - acc: 0.8468
Epoch 47/100
 - 20s - loss: 0.3569 - acc: 0.8469
Epoch 48/100
 - 19s - loss: 0.3575 - acc: 0.8467
Epoch 49/100
 - 20s - loss: 0.3568 - acc: 0.8467
Epoch 50/100
 - 19s - loss: 0.3582 - acc: 0.8467
Epoch 51/100
 - 19s - loss: 0.3543 - acc: 0.8474
Epoch 52/100
 - 19s - loss: 0.3580 - acc: 0.8468
Epoch 53/100
 - 19s - loss: 0.3542 - acc: 0.8470
Epoch 54/100
 - 19s - loss: 0.3574 - acc: 0.8470
Epoch 55/100
 - 20s - loss: 0.3537 - acc: 0.8473
Epoch 56/100
 - 19s - loss: 0.3553 - acc: 0.8472
Epoch 57/100
 - 18s - loss: 0.3591 - acc: 0.8472
Epoch 58/100
 - 19s - loss: 0.3532 - acc: 0.8476
Epoch 59/100
 - 19s - loss: 0.3550 - acc: 0.8476
Epoch 60/100
 - 18s - loss: 0.3532 - acc: 0.8479
Epoch 61/100
 - 18s - loss: 0.3527 - acc: 0.8477
Epoch 62/100
 - 18s - loss: 0.3530 - acc: 0.8476
Epoch 63/100
 - 19s - loss: 0.3525 - acc: 0.8481
Epoch 64/100
 - 18s - loss: 0.3544 - acc: 0.8480
Epoch 65/100
 - 19s - loss: 0.3526 - acc: 0.8480
Epoch 66/100
 - 18s - loss: 0.3548 - acc: 0.8479
Epoch 67/100
 - 18s - loss: 0.3533 - acc: 0.8479
Epoch 68/100
 - 18s - loss: 0.3558 - acc: 0.8482
Epoch 69/100
 - 18s - loss: 0.3533 - acc: 0.8482
Epoch 70/100
 - 18s - loss: 0.3575 - acc: 0.8484
Epoch 71/100
 - 18s - loss: 0.3571 - acc: 0.8480
Epoch 72/100
 - 18s - loss: 0.3576 - acc: 0.8482
Epoch 73/100
 - 18s - loss: 0.3570 - acc: 0.8486
Epoch 74/100
 - 18s - loss: 0.3567 - acc: 0.8487
Epoch 75/100
 - 18s - loss: 0.3574 - acc: 0.8486
Epoch 76/100
 - 18s - loss: 0.3569 - acc: 0.8486
Epoch 77/100
 - 18s - loss: 0.3565 - acc: 0.8492
Epoch 78/100
 - 18s - loss: 0.3572 - acc: 0.8489
Epoch 79/100
 - 18s - loss: 0.3567 - acc: 0.8491
Epoch 80/100
 - 18s - loss: 0.3564 - acc: 0.8493
Epoch 81/100
 - 18s - loss: 0.3561 - acc: 0.8494
Epoch 82/100
 - 18s - loss: 0.3582 - acc: 0.8489
Epoch 83/100
 - 18s - loss: 0.3556 - acc: 0.8491
Epoch 84/100
 - 18s - loss: 0.3559 - acc: 0.8495
Epoch 85/100
 - 18s - loss: 0.3554 - acc: 0.8492
Epoch 86/100
 - 19s - loss: 0.3581 - acc: 0.8489
Epoch 87/100
 - 18s - loss: 0.3555 - acc: 0.8492
Epoch 88/100
 - 18s - loss: 0.3554 - acc: 0.8491
Epoch 89/100
 - 18s - loss: 0.3560 - acc: 0.8498
Epoch 90/100
 - 18s - loss: 0.3556 - acc: 0.8497
Epoch 91/100
 - 19s - loss: 0.3566 - acc: 0.8496
Epoch 92/100
 - 18s - loss: 0.3547 - acc: 0.8495
Epoch 93/100
 - 18s - loss: 0.3547 - acc: 0.8500
Epoch 94/100
 - 18s - loss: 0.3548 - acc: 0.8497
Epoch 95/100
 - 18s - loss: 0.3547 - acc: 0.8498
Epoch 96/100
 - 18s - loss: 0.3551 - acc: 0.8495
Epoch 97/100
 - 18s - loss: 0.3546 - acc: 0.8500
Epoch 98/100
 - 18s - loss: 0.3544 - acc: 0.8497
Epoch 99/100
 - 25s - loss: 0.3546 - acc: 0.8498
Epoch 100/100
 - 837s - loss: 0.3547 - acc: 0.8501

## Quantify our Trained Model

In [17]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 0.39831336800920697, Accuracy: 0.8340239427736614

## Make Predictions

In [18]:
encoded_predictions = model.predict_classes(X_test_scaled[:5])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\benfraund\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [19]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:5])}")

Predicted classes: ['Violent' 'Violent' 'Property' 'Property' 'Property']
Actual Labels: ['Violent', 'Violent', 'Property', 'Property', 'Property']

## Save the Trained Model

In [20]:
model.save("violent_crime_model_trained.h5")

## Load FBI Crime Category Data

In [22]:
fbi_crime = pd.read_csv('la_crime_incl_fbi_cat.csv')
fbi_crime = fbi_crime.drop([0])
#crime = crime.set_index('dr_no')
fbi_crime['date_occ'] = fbi_crime['date_occ'].apply(pd.to_numeric)
fbi_crime['status'] = fbi_crime['status'].fillna('-')
fbi_crime['vict_sex'] = fbi_crime['vict_sex'].fillna('-')
fbi_crime['vict_descent'] = fbi_crime['vict_descent'].fillna('-')
fbi_crime.head()

,dr_no,area_id,date_occ,date_rptd,longitude,latitude,mocodes,premis_cd,rpt_dist_no,status,hour_occ,minute_occ,vict_age,vict_descent,vict_sex,FBI_Category
1,214,14,20170801,20170801,-118.4262,34.0106,NaN,104.0,1435,IC,2,0,16.0,-,-,Motor Vehicle Theft
2,405,5,20181031,20181102,-118.2468,33.7926,NaN,101.0,519,IC,21,0,17.0,-,-,Motor Vehicle Theft
3,415,15,20170822,20170822,-118.4137,34.1867,NaN,108.0,1523,IC,13,45,16.0,-,-,Motor Vehicle Theft
4,418,18,20130318,20130319,-118.2717,33.9420,NaN,101.0,1823,IC,20,30,12.0,-,-,Motor Vehicle Theft
5,605,5,20120606,20120607,-118.2640,33.8028,NaN,101.0,518,IC,23,0,11.0,-,-,Motor Vehicle Theft

In [23]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
fbi_crime = fbi_crime.join(pd.DataFrame(mlb.fit_transform(fbi_crime.pop('vict_descent')),
                               columns=mlb.classes_ + "(vict_descent)",
                               index=fbi_crime.index))

fbi_crime = fbi_crime.join(pd.DataFrame(mlb.fit_transform(fbi_crime.pop('vict_sex')),
                               columns=mlb.classes_ + "(vict_sex)",
                               index=fbi_crime.index))

fbi_crime = fbi_crime.join(pd.DataFrame(mlb.fit_transform(fbi_crime.pop('status')),
                               columns=mlb.classes_ + "(status)",
                               index=fbi_crime.index))

fbi_crime.head()

,dr_no,area_id,date_occ,date_rptd,longitude,latitude,mocodes,premis_cd,rpt_dist_no,hour_occ,...,X(vict_sex),-(status),1(status),3(status),9(status),A(status),C(status),I(status),J(status),O(status)
1,214,14,20170801,20170801,-118.4262,34.0106,NaN,104.0,1435,2,...,0,0,0,0,0,0,1,1,0,0
2,405,5,20181031,20181102,-118.2468,33.7926,NaN,101.0,519,21,...,0,0,0,0,0,0,1,1,0,0
3,415,15,20170822,20170822,-118.4137,34.1867,NaN,108.0,1523,13,...,0,0,0,0,0,0,1,1,0,0
4,418,18,20130318,20130319,-118.2717,33.9420,NaN,101.0,1823,20,...,0,0,0,0,0,0,1,1,0,0
5,605,5,20120606,20120607,-118.2640,33.8028,NaN,101.0,518,23,...,0,0,0,0,0,0,1,1,0,0

In [24]:
fbi_crime['mocodes'].isna().sum()

175950

In [25]:
#crime['mocodes'] = crime['mocodes'].fillna('["-"]')
fbi_crime['mocodes'].isna().sum()
fbi_crime = fbi_crime.dropna()
fbi_crime.count()

dr_no              714750
area_id            714750
date_occ           714750
date_rptd          714750
longitude          714750
latitude           714750
mocodes            714750
premis_cd          714750
rpt_dist_no        714750
hour_occ           714750
minute_occ         714750
vict_age           714750
FBI_Category       714750
-(vict_descent)    714750
A(vict_descent)    714750
B(vict_descent)    714750
C(vict_descent)    714750
D(vict_descent)    714750
F(vict_descent)    714750
G(vict_descent)    714750
H(vict_descent)    714750
I(vict_descent)    714750
J(vict_descent)    714750
K(vict_descent)    714750
L(vict_descent)    714750
O(vict_descent)    714750
P(vict_descent)    714750
S(vict_descent)    714750
U(vict_descent)    714750
V(vict_descent)    714750
W(vict_descent)    714750
X(vict_descent)    714750
Z(vict_descent)    714750
-(vict_sex)        714750
F(vict_sex)        714750
H(vict_sex)        714750
M(vict_sex)        714750
N(vict_sex)        714750
X(vict_sex)        714750
-(status)          714750
1(status)          714750
3(status)          714750
9(status)          714750
A(status)          714750
C(status)          714750
I(status)          714750
J(status)          714750
O(status)          714750
dtype: int64

## One-hot Encode mocodes (fbi_crime)

In [26]:
from sklearn.preprocessing import LabelEncoder

mocodes = fbi_crime.values[:, 7]

label_encoder = LabelEncoder()
label_encoder.fit(mocodes)
mocodes2 = label_encoder.transform(mocodes)
mocodes2

array([136, 196, 120, ...,   7, 135,  59], dtype=int64)

In [27]:
from keras.utils import to_categorical

mocodes3 = to_categorical(mocodes2)
mocodes3

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
for label, original_class in zip(mocodes3, mocodes):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [28]:
new_mocodes = pd.DataFrame(mocodes3)
new_mocodes.head()

,0,1,2,3,4,5,6,7,8,9,...,296,297,298,299,300,301,302,303,304,305
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
fbi_crime = pd.merge(fbi_crime, new_mocodes, left_index=True, right_index=True)

fbi_crime.head()

,dr_no,area_id,date_occ,date_rptd,longitude,latitude,mocodes,premis_cd,rpt_dist_no,hour_occ,...,296,297,298,299,300,301,302,303,304,305
12,80611351,6,20110612,20110613,-118.3348,34.1032,"[""0344"", ""1607""]",502.0,636,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,91231932,3,20110514,20110514,-118.3290,34.0060,"[""0430"", ""1100"", ""1414"", ""0906""]",735.0,393,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,100100506,1,20100104,20100105,-118.2577,34.0480,"[""0344"", ""1402""]",404.0,162,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,100100508,1,20100107,20100108,-118.2643,34.0389,"[""0344""]",101.0,182,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,100100509,1,20100108,20100109,-118.2427,34.0435,"[""0416""]",710.0,157,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
fbi_crime = fbi_crime.drop("mocodes", axis=1)

In [31]:
fbi_crime['vict_age'].isna().sum()

0

In [32]:
fbi_crime_cln = fbi_crime.dropna()

In [33]:
X = fbi_crime_cln.drop("FBI_Category", axis=1)
y = fbi_crime_cln["FBI_Category"]
print(X.shape, y.shape)

(539619, 352) (539619,)

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

# Create a Deep Learning Model (fbi_crime)

In [36]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=352))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=8, activation='softmax'))

In [37]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 17s - loss: 1.1179 - acc: 0.5701
Epoch 2/100
 - 17s - loss: 1.0485 - acc: 0.5976
Epoch 3/100
 - 17s - loss: 1.0308 - acc: 0.6040
Epoch 4/100
 - 17s - loss: 1.0198 - acc: 0.6087
Epoch 5/100
 - 17s - loss: 1.0110 - acc: 0.6125
Epoch 6/100
 - 16s - loss: 1.0062 - acc: 0.6144
Epoch 7/100
 - 17s - loss: 1.0019 - acc: 0.6165
Epoch 8/100
 - 17s - loss: 0.9974 - acc: 0.6172
Epoch 9/100
 - 17s - loss: 0.9952 - acc: 0.6190
Epoch 10/100
 - 17s - loss: 0.9920 - acc: 0.6202
Epoch 11/100
 - 17s - loss: 0.9899 - acc: 0.6207
Epoch 12/100
 - 17s - loss: 0.9872 - acc: 0.6221
Epoch 13/100
 - 17s - loss: 0.9853 - acc: 0.6227
Epoch 14/100
 - 17s - loss: 0.9837 - acc: 0.6226
Epoch 15/100
 - 17s - loss: 0.9821 - acc: 0.6236
Epoch 16/100
 - 16s - loss: 0.9805 - acc: 0.6244
Epoch 17/100
 - 17s - loss: 0.9793 - acc: 0.6247
Epoch 18/100
 - 17s - loss: 0.9792 - acc: 0.6256
Epoch 19/100
 - 17s - loss: 0.9770 - acc: 0.6264
Epoch 20/100
 - 17s - loss: 0.9767 - acc: 0.6267
Epoch 21/100
 - 18s - loss: 0.9763 - acc: 0.6273
Epoch 22/100
 - 18s - loss: 0.9761 - acc: 0.6274
Epoch 23/100
 - 18s - loss: 0.9771 - acc: 0.6278
Epoch 24/100
 - 18s - loss: 0.9733 - acc: 0.6284
Epoch 25/100
 - 18s - loss: 0.9715 - acc: 0.6285
Epoch 26/100
 - 18s - loss: 0.9728 - acc: 0.6281
Epoch 27/100
 - 18s - loss: 0.9698 - acc: 0.6288
Epoch 28/100
 - 19s - loss: 0.9697 - acc: 0.6301
Epoch 29/100
 - 19s - loss: 0.9698 - acc: 0.6296
Epoch 30/100
 - 19s - loss: 0.9687 - acc: 0.6307
Epoch 31/100
 - 19s - loss: 0.9672 - acc: 0.6307
Epoch 32/100
 - 19s - loss: 0.9665 - acc: 0.6321
Epoch 33/100
 - 18s - loss: 0.9674 - acc: 0.6317
Epoch 34/100
 - 18s - loss: 0.9660 - acc: 0.6318
Epoch 35/100
 - 18s - loss: 0.9655 - acc: 0.6323
Epoch 36/100
 - 18s - loss: 0.9661 - acc: 0.6324
Epoch 37/100
 - 20s - loss: 0.9721 - acc: 0.6322
Epoch 38/100
 - 19s - loss: 0.9649 - acc: 0.6332
Epoch 39/100
 - 21s - loss: 0.9637 - acc: 0.6336
Epoch 40/100
 - 23s - loss: 0.9628 - acc: 0.6330
Epoch 41/100
 - 21s - loss: 0.9618 - acc: 0.6336
Epoch 42/100
 - 22s - loss: 0.9612 - acc: 0.6336
Epoch 43/100
 - 25s - loss: 0.9612 - acc: 0.6337
Epoch 44/100
 - 25s - loss: 0.9639 - acc: 0.6338
Epoch 45/100
 - 24s - loss: 0.9644 - acc: 0.6339
Epoch 46/100
 - 23s - loss: 0.9659 - acc: 0.6339
Epoch 47/100
 - 22s - loss: 0.9655 - acc: 0.6345
Epoch 48/100
 - 21s - loss: 0.9630 - acc: 0.6338
Epoch 49/100
 - 21s - loss: 0.9628 - acc: 0.6346
Epoch 50/100
 - 21s - loss: 0.9617 - acc: 0.6348
Epoch 51/100
 - 20s - loss: 0.9597 - acc: 0.6349
Epoch 52/100
 - 20s - loss: 0.9650 - acc: 0.6352
Epoch 53/100
 - 20s - loss: 0.9589 - acc: 0.6347
Epoch 54/100
 - 20s - loss: 0.9612 - acc: 0.6352
Epoch 55/100
 - 20s - loss: 0.9589 - acc: 0.6358
Epoch 56/100
 - 20s - loss: 0.9739 - acc: 0.6355
Epoch 57/100
 - 18s - loss: 0.9658 - acc: 0.6351
Epoch 58/100
 - 17s - loss: 0.9587 - acc: 0.6358
Epoch 59/100
 - 17s - loss: 0.9660 - acc: 0.6356
Epoch 60/100
 - 17s - loss: 0.9582 - acc: 0.6359
Epoch 61/100
 - 17s - loss: 0.9586 - acc: 0.6359
Epoch 62/100
 - 17s - loss: 0.9567 - acc: 0.6356
Epoch 63/100
 - 17s - loss: 0.9562 - acc: 0.6364
Epoch 64/100
 - 17s - loss: 0.9905 - acc: 0.6367
Epoch 65/100
 - 17s - loss: 0.9633 - acc: 0.6373
Epoch 66/100
 - 18s - loss: 0.9560 - acc: 0.6369
Epoch 67/100
 - 18s - loss: 0.9564 - acc: 0.6370
Epoch 68/100
 - 18s - loss: 1.0566 - acc: 0.6361
Epoch 69/100
 - 18s - loss: 1.0140 - acc: 0.6366
Epoch 70/100
 - 18s - loss: 0.9935 - acc: 0.6368
Epoch 71/100
 - 18s - loss: 0.9750 - acc: 0.6372
Epoch 72/100
 - 19s - loss: 0.9748 - acc: 0.6362
Epoch 73/100
 - 19s - loss: 0.9662 - acc: 0.6371
Epoch 74/100
 - 19s - loss: 0.9765 - acc: 0.6377
Epoch 75/100
 - 19s - loss: 0.9650 - acc: 0.6374
Epoch 76/100
 - 19s - loss: 0.9634 - acc: 0.6372
Epoch 77/100
 - 19s - loss: 0.9661 - acc: 0.6376
Epoch 78/100
 - 21s - loss: 0.9644 - acc: 0.6369
Epoch 79/100
 - 18s - loss: 0.9654 - acc: 0.6367
Epoch 80/100
 - 12946s - loss: 0.9617 - acc: 0.6374
Epoch 81/100
 - 20s - loss: 0.9626 - acc: 0.6379
Epoch 82/100
 - 17s - loss: 0.9672 - acc: 0.6377
Epoch 83/100
 - 17s - loss: 0.9621 - acc: 0.6383
Epoch 84/100
 - 17s - loss: 0.9652 - acc: 0.6381
Epoch 85/100
 - 17s - loss: 0.9663 - acc: 0.6378
Epoch 86/100
 - 17s - loss: 0.9633 - acc: 0.6380
Epoch 87/100
 - 17s - loss: 0.9631 - acc: 0.6382
Epoch 88/100
 - 17s - loss: 0.9624 - acc: 0.6380
Epoch 89/100
 - 17s - loss: 0.9621 - acc: 0.6391
Epoch 90/100
 - 17s - loss: 0.9642 - acc: 0.6384
Epoch 91/100
 - 17s - loss: 0.9568 - acc: 0.6392
Epoch 92/100
 - 17s - loss: 0.9584 - acc: 0.6391
Epoch 93/100
 - 17s - loss: 0.9583 - acc: 0.6387
Epoch 94/100
 - 17s - loss: 0.9609 - acc: 0.6394
Epoch 95/100
 - 17s - loss: 0.9619 - acc: 0.6388
Epoch 96/100
 - 17s - loss: 0.9580 - acc: 0.6392
Epoch 97/100
 - 17s - loss: 0.9577 - acc: 0.6394
Epoch 98/100
 - 17s - loss: 0.9563 - acc: 0.6392
Epoch 99/100
 - 17s - loss: 0.9654 - acc: 0.6387
Epoch 100/100
 - 17s - loss: 0.9579 - acc: 0.6393

## Quantify our Trained Model

In [38]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 1.0009436212880198, Accuracy: 0.6256476779960684

## Make Predictions

In [39]:
encoded_predictions = model.predict_classes(X_test_scaled[:5])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\benfraund\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [40]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:5])}")

Predicted classes: ['Personal/Other Theft' 'Robbery' 'BTFV' 'Burglary' 'BTFV']
Actual Labels: ['Personal/Other Theft', 'Burglary', 'Personal/Other Theft', 'Burglary', 'BTFV']

In [41]:
model.save("fbi_category_model_trained.h5")